{{- if .Values.bff.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-bff
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vpc-network-bff
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: bff
{{- end }}
