{{- if .Values.consolePlugin.enabled }}
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: vpc-network-management
spec:
  displayName: VPC Network Management
  backend:
    type: Service
    service:
      basePath: /
      name: {{ .Release.Name }}-console-plugin
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.consolePlugin.port }}
  proxy:
  - alias: bff
    authorization: UserToken
    endpoint:
      type: Service
      service:
        name: {{ .Release.Name }}-bff
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.bff.port }}
{{- end }}
