apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpc-network-developer
  labels:
    app.kubernetes.io/name: roks-vpc-network-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
# Read-only access to VPC network resources
- apiGroups:
  - vpc.roks.ibm.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
