//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeEVPN) DeepCopyInto(out *BridgeEVPN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeEVPN.
func (in *BridgeEVPN) DeepCopy() *BridgeEVPN {
	if in == nil {
		return nil
	}
	out := new(BridgeEVPN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeL2VPN) DeepCopyInto(out *BridgeL2VPN) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeL2VPN.
func (in *BridgeL2VPN) DeepCopy() *BridgeL2VPN {
	if in == nil {
		return nil
	}
	out := new(BridgeL2VPN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeMTU) DeepCopyInto(out *BridgeMTU) {
	*out = *in
	if in.TunnelMTU != nil {
		in, out := &in.TunnelMTU, &out.TunnelMTU
		*out = new(int32)
		**out = **in
	}
	if in.MSSClamp != nil {
		in, out := &in.MSSClamp, &out.MSSClamp
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeMTU.
func (in *BridgeMTU) DeepCopy() *BridgeMTU {
	if in == nil {
		return nil
	}
	out := new(BridgeMTU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeNetworkRef) DeepCopyInto(out *BridgeNetworkRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeNetworkRef.
func (in *BridgeNetworkRef) DeepCopy() *BridgeNetworkRef {
	if in == nil {
		return nil
	}
	out := new(BridgeNetworkRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeRemote) DeepCopyInto(out *BridgeRemote) {
	*out = *in
	if in.WireGuard != nil {
		in, out := &in.WireGuard, &out.WireGuard
		*out = new(BridgeWireGuard)
		(*in).DeepCopyInto(*out)
	}
	if in.L2VPN != nil {
		in, out := &in.L2VPN, &out.L2VPN
		*out = new(BridgeL2VPN)
		**out = **in
	}
	if in.EVPN != nil {
		in, out := &in.EVPN, &out.EVPN
		*out = new(BridgeEVPN)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeRemote.
func (in *BridgeRemote) DeepCopy() *BridgeRemote {
	if in == nil {
		return nil
	}
	out := new(BridgeRemote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeWireGuard) DeepCopyInto(out *BridgeWireGuard) {
	*out = *in
	out.PrivateKey = in.PrivateKey
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeWireGuard.
func (in *BridgeWireGuard) DeepCopy() *BridgeWireGuard {
	if in == nil {
		return nil
	}
	out := new(BridgeWireGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNATRule) DeepCopyInto(out *DNATRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNATRule.
func (in *DNATRule) DeepCopy() *DNATRule {
	if in == nil {
		return nil
	}
	out := new(DNATRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSFilteringConfig) DeepCopyInto(out *DNSFilteringConfig) {
	*out = *in
	if in.Blocklists != nil {
		in, out := &in.Blocklists, &out.Blocklists
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Allowlist != nil {
		in, out := &in.Allowlist, &out.Allowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Denylist != nil {
		in, out := &in.Denylist, &out.Denylist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSFilteringConfig.
func (in *DNSFilteringConfig) DeepCopy() *DNSFilteringConfig {
	if in == nil {
		return nil
	}
	out := new(DNSFilteringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLocalConfig) DeepCopyInto(out *DNSLocalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLocalConfig.
func (in *DNSLocalConfig) DeepCopy() *DNSLocalConfig {
	if in == nil {
		return nil
	}
	out := new(DNSLocalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSUpstreamConfig) DeepCopyInto(out *DNSUpstreamConfig) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]DNSUpstreamServer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSUpstreamConfig.
func (in *DNSUpstreamConfig) DeepCopy() *DNSUpstreamConfig {
	if in == nil {
		return nil
	}
	out := new(DNSUpstreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSUpstreamServer) DeepCopyInto(out *DNSUpstreamServer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSUpstreamServer.
func (in *DNSUpstreamServer) DeepCopy() *DNSUpstreamServer {
	if in == nil {
		return nil
	}
	out := new(DNSUpstreamServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallRule) DeepCopyInto(out *FirewallRule) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallRule.
func (in *FirewallRule) DeepCopy() *FirewallRule {
	if in == nil {
		return nil
	}
	out := new(FirewallRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloatingIP) DeepCopyInto(out *FloatingIP) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloatingIP.
func (in *FloatingIP) DeepCopy() *FloatingIP {
	if in == nil {
		return nil
	}
	out := new(FloatingIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FloatingIP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloatingIPList) DeepCopyInto(out *FloatingIPList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FloatingIP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloatingIPList.
func (in *FloatingIPList) DeepCopy() *FloatingIPList {
	if in == nil {
		return nil
	}
	out := new(FloatingIPList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FloatingIPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloatingIPSpec) DeepCopyInto(out *FloatingIPSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloatingIPSpec.
func (in *FloatingIPSpec) DeepCopy() *FloatingIPSpec {
	if in == nil {
		return nil
	}
	out := new(FloatingIPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloatingIPStatus) DeepCopyInto(out *FloatingIPStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloatingIPStatus.
func (in *FloatingIPStatus) DeepCopy() *FloatingIPStatus {
	if in == nil {
		return nil
	}
	out := new(FloatingIPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayFirewall) DeepCopyInto(out *GatewayFirewall) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]FirewallRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayFirewall.
func (in *GatewayFirewall) DeepCopy() *GatewayFirewall {
	if in == nil {
		return nil
	}
	out := new(GatewayFirewall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayFloatingIP) DeepCopyInto(out *GatewayFloatingIP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayFloatingIP.
func (in *GatewayFloatingIP) DeepCopy() *GatewayFloatingIP {
	if in == nil {
		return nil
	}
	out := new(GatewayFloatingIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayInterface) DeepCopyInto(out *GatewayInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayInterface.
func (in *GatewayInterface) DeepCopy() *GatewayInterface {
	if in == nil {
		return nil
	}
	out := new(GatewayInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNAT) DeepCopyInto(out *GatewayNAT) {
	*out = *in
	if in.SNAT != nil {
		in, out := &in.SNAT, &out.SNAT
		*out = make([]SNATRule, len(*in))
		copy(*out, *in)
	}
	if in.DNAT != nil {
		in, out := &in.DNAT, &out.DNAT
		*out = make([]DNATRule, len(*in))
		copy(*out, *in)
	}
	if in.NoNAT != nil {
		in, out := &in.NoNAT, &out.NoNAT
		*out = make([]NoNATRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNAT.
func (in *GatewayNAT) DeepCopy() *GatewayNAT {
	if in == nil {
		return nil
	}
	out := new(GatewayNAT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPublicAddressRange) DeepCopyInto(out *GatewayPublicAddressRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPublicAddressRange.
func (in *GatewayPublicAddressRange) DeepCopy() *GatewayPublicAddressRange {
	if in == nil {
		return nil
	}
	out := new(GatewayPublicAddressRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayTransit) DeepCopyInto(out *GatewayTransit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayTransit.
func (in *GatewayTransit) DeepCopy() *GatewayTransit {
	if in == nil {
		return nil
	}
	out := new(GatewayTransit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayUplink) DeepCopyInto(out *GatewayUplink) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayUplink.
func (in *GatewayUplink) DeepCopy() *GatewayUplink {
	if in == nil {
		return nil
	}
	out := new(GatewayUplink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoNATRule) DeepCopyInto(out *NoNATRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoNATRule.
func (in *NoNATRule) DeepCopy() *NoNATRule {
	if in == nil {
		return nil
	}
	out := new(NoNATRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteAdvertisement) DeepCopyInto(out *RouteAdvertisement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteAdvertisement.
func (in *RouteAdvertisement) DeepCopy() *RouteAdvertisement {
	if in == nil {
		return nil
	}
	out := new(RouteAdvertisement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPDNSConfig) DeepCopyInto(out *DHCPDNSConfig) {
	*out = *in
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SearchDomains != nil {
		in, out := &in.SearchDomains, &out.SearchDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPDNSConfig.
func (in *DHCPDNSConfig) DeepCopy() *DHCPDNSConfig {
	if in == nil {
		return nil
	}
	out := new(DHCPDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPNetworkStatus) DeepCopyInto(out *DHCPNetworkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPNetworkStatus.
func (in *DHCPNetworkStatus) DeepCopy() *DHCPNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(DHCPNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPOptions) DeepCopyInto(out *DHCPOptions) {
	*out = *in
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int32)
		**out = **in
	}
	if in.NTPServers != nil {
		in, out := &in.NTPServers, &out.NTPServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPOptions.
func (in *DHCPOptions) DeepCopy() *DHCPOptions {
	if in == nil {
		return nil
	}
	out := new(DHCPOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPStaticReservation) DeepCopyInto(out *DHCPStaticReservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPStaticReservation.
func (in *DHCPStaticReservation) DeepCopy() *DHCPStaticReservation {
	if in == nil {
		return nil
	}
	out := new(DHCPStaticReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDHCP) DeepCopyInto(out *NetworkDHCP) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Range != nil {
		in, out := &in.Range, &out.Range
		*out = new(NetworkDHCPRange)
		**out = **in
	}
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make([]DHCPStaticReservation, len(*in))
		copy(*out, *in)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DHCPDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(DHCPOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDHCP.
func (in *NetworkDHCP) DeepCopy() *NetworkDHCP {
	if in == nil {
		return nil
	}
	out := new(NetworkDHCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDHCPRange) DeepCopyInto(out *NetworkDHCPRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDHCPRange.
func (in *NetworkDHCPRange) DeepCopy() *NetworkDHCPRange {
	if in == nil {
		return nil
	}
	out := new(NetworkDHCPRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterDHCP) DeepCopyInto(out *RouterDHCP) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DHCPDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(DHCPOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterDHCP.
func (in *RouterDHCP) DeepCopy() *RouterDHCP {
	if in == nil {
		return nil
	}
	out := new(RouterDHCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterIDS) DeepCopyInto(out *RouterIDS) {
	*out = *in
	if in.NFQueueNum != nil {
		in, out := &in.NFQueueNum, &out.NFQueueNum
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterIDS.
func (in *RouterIDS) DeepCopy() *RouterIDS {
	if in == nil {
		return nil
	}
	out := new(RouterIDS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterNetwork) DeepCopyInto(out *RouterNetwork) {
	*out = *in
	if in.DHCP != nil {
		in, out := &in.DHCP, &out.DHCP
		*out = new(NetworkDHCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterNetwork.
func (in *RouterNetwork) DeepCopy() *RouterNetwork {
	if in == nil {
		return nil
	}
	out := new(RouterNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterNetworkStatus) DeepCopyInto(out *RouterNetworkStatus) {
	*out = *in
	if in.DHCP != nil {
		in, out := &in.DHCP, &out.DHCP
		*out = new(DHCPNetworkStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterNetworkStatus.
func (in *RouterNetworkStatus) DeepCopy() *RouterNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(RouterNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterPodSpec) DeepCopyInto(out *RouterPodSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterPodSpec.
func (in *RouterPodSpec) DeepCopy() *RouterPodSpec {
	if in == nil {
		return nil
	}
	out := new(RouterPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTransit) DeepCopyInto(out *RouterTransit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTransit.
func (in *RouterTransit) DeepCopy() *RouterTransit {
	if in == nil {
		return nil
	}
	out := new(RouterTransit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNATRule) DeepCopyInto(out *SNATRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNATRule.
func (in *SNATRule) DeepCopy() *SNATRule {
	if in == nil {
		return nil
	}
	out := new(SNATRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANAttachment) DeepCopyInto(out *VLANAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANAttachment.
func (in *VLANAttachment) DeepCopy() *VLANAttachment {
	if in == nil {
		return nil
	}
	out := new(VLANAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLANAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANAttachmentList) DeepCopyInto(out *VLANAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VLANAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANAttachmentList.
func (in *VLANAttachmentList) DeepCopy() *VLANAttachmentList {
	if in == nil {
		return nil
	}
	out := new(VLANAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLANAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANAttachmentSpec) DeepCopyInto(out *VLANAttachmentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANAttachmentSpec.
func (in *VLANAttachmentSpec) DeepCopy() *VLANAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(VLANAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANAttachmentStatus) DeepCopyInto(out *VLANAttachmentStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANAttachmentStatus.
func (in *VLANAttachmentStatus) DeepCopy() *VLANAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(VLANAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMReference) DeepCopyInto(out *VMReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMReference.
func (in *VMReference) DeepCopy() *VMReference {
	if in == nil {
		return nil
	}
	out := new(VMReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VNISpec) DeepCopyInto(out *VNISpec) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VMRef != nil {
		in, out := &in.VMRef, &out.VMRef
		*out = new(VMReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VNISpec.
func (in *VNISpec) DeepCopy() *VNISpec {
	if in == nil {
		return nil
	}
	out := new(VNISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VNIStatus) DeepCopyInto(out *VNIStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VNIStatus.
func (in *VNIStatus) DeepCopy() *VNIStatus {
	if in == nil {
		return nil
	}
	out := new(VNIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCGateway) DeepCopyInto(out *VPCGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCGateway.
func (in *VPCGateway) DeepCopy() *VPCGateway {
	if in == nil {
		return nil
	}
	out := new(VPCGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCGatewayList) DeepCopyInto(out *VPCGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCGatewayList.
func (in *VPCGatewayList) DeepCopy() *VPCGatewayList {
	if in == nil {
		return nil
	}
	out := new(VPCGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCGatewaySpec) DeepCopyInto(out *VPCGatewaySpec) {
	*out = *in
	in.Uplink.DeepCopyInto(&out.Uplink)
	out.Transit = in.Transit
	if in.VPCRoutes != nil {
		in, out := &in.VPCRoutes, &out.VPCRoutes
		*out = make([]VPCRouteSpec, len(*in))
		copy(*out, *in)
	}
	if in.NAT != nil {
		in, out := &in.NAT, &out.NAT
		*out = new(GatewayNAT)
		(*in).DeepCopyInto(*out)
	}
	if in.FloatingIP != nil {
		in, out := &in.FloatingIP, &out.FloatingIP
		*out = new(GatewayFloatingIP)
		**out = **in
	}
	if in.PublicAddressRange != nil {
		in, out := &in.PublicAddressRange, &out.PublicAddressRange
		*out = new(GatewayPublicAddressRange)
		**out = **in
	}
	if in.Firewall != nil {
		in, out := &in.Firewall, &out.Firewall
		*out = new(GatewayFirewall)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(RouterPodSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCGatewaySpec.
func (in *VPCGatewaySpec) DeepCopy() *VPCGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(VPCGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCGatewayStatus) DeepCopyInto(out *VPCGatewayStatus) {
	*out = *in
	if in.IngressRouteIDs != nil {
		in, out := &in.IngressRouteIDs, &out.IngressRouteIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VPCRouteIDs != nil {
		in, out := &in.VPCRouteIDs, &out.VPCRouteIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]GatewayInterface, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCGatewayStatus.
func (in *VPCGatewayStatus) DeepCopy() *VPCGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(VPCGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDNSPolicy) DeepCopyInto(out *VPCDNSPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDNSPolicy.
func (in *VPCDNSPolicy) DeepCopy() *VPCDNSPolicy {
	if in == nil {
		return nil
	}
	out := new(VPCDNSPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCDNSPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDNSPolicyList) DeepCopyInto(out *VPCDNSPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCDNSPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDNSPolicyList.
func (in *VPCDNSPolicyList) DeepCopy() *VPCDNSPolicyList {
	if in == nil {
		return nil
	}
	out := new(VPCDNSPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCDNSPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDNSPolicySpec) DeepCopyInto(out *VPCDNSPolicySpec) {
	*out = *in
	if in.Upstream != nil {
		in, out := &in.Upstream, &out.Upstream
		*out = new(DNSUpstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Filtering != nil {
		in, out := &in.Filtering, &out.Filtering
		*out = new(DNSFilteringConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalDNS != nil {
		in, out := &in.LocalDNS, &out.LocalDNS
		*out = new(DNSLocalConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDNSPolicySpec.
func (in *VPCDNSPolicySpec) DeepCopy() *VPCDNSPolicySpec {
	if in == nil {
		return nil
	}
	out := new(VPCDNSPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDNSPolicyStatus) DeepCopyInto(out *VPCDNSPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDNSPolicyStatus.
func (in *VPCDNSPolicyStatus) DeepCopy() *VPCDNSPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(VPCDNSPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCL2Bridge) DeepCopyInto(out *VPCL2Bridge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCL2Bridge.
func (in *VPCL2Bridge) DeepCopy() *VPCL2Bridge {
	if in == nil {
		return nil
	}
	out := new(VPCL2Bridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCL2Bridge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCL2BridgeList) DeepCopyInto(out *VPCL2BridgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCL2Bridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCL2BridgeList.
func (in *VPCL2BridgeList) DeepCopy() *VPCL2BridgeList {
	if in == nil {
		return nil
	}
	out := new(VPCL2BridgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCL2BridgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCL2BridgeSpec) DeepCopyInto(out *VPCL2BridgeSpec) {
	*out = *in
	out.NetworkRef = in.NetworkRef
	in.Remote.DeepCopyInto(&out.Remote)
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(BridgeMTU)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(RouterPodSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCL2BridgeSpec.
func (in *VPCL2BridgeSpec) DeepCopy() *VPCL2BridgeSpec {
	if in == nil {
		return nil
	}
	out := new(VPCL2BridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCL2BridgeStatus) DeepCopyInto(out *VPCL2BridgeStatus) {
	*out = *in
	if in.LastHandshake != nil {
		in, out := &in.LastHandshake, &out.LastHandshake
		*out = (*in).DeepCopy()
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCL2BridgeStatus.
func (in *VPCL2BridgeStatus) DeepCopy() *VPCL2BridgeStatus {
	if in == nil {
		return nil
	}
	out := new(VPCL2BridgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCVPNGateway) DeepCopyInto(out *VPCVPNGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCVPNGateway.
func (in *VPCVPNGateway) DeepCopy() *VPCVPNGateway {
	if in == nil {
		return nil
	}
	out := new(VPCVPNGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCVPNGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCVPNGatewayList) DeepCopyInto(out *VPCVPNGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCVPNGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCVPNGatewayList.
func (in *VPCVPNGatewayList) DeepCopy() *VPCVPNGatewayList {
	if in == nil {
		return nil
	}
	out := new(VPCVPNGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCVPNGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCVPNGatewaySpec) DeepCopyInto(out *VPCVPNGatewaySpec) {
	*out = *in
	if in.WireGuard != nil {
		in, out := &in.WireGuard, &out.WireGuard
		*out = new(VPNWireGuardConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IPsec != nil {
		in, out := &in.IPsec, &out.IPsec
		*out = new(VPNIPsecConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Tunnels != nil {
		in, out := &in.Tunnels, &out.Tunnels
		*out = make([]VPNTunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemoteAccess != nil {
		in, out := &in.RemoteAccess, &out.RemoteAccess
		*out = new(VPNRemoteAccess)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalNetworks != nil {
		in, out := &in.LocalNetworks, &out.LocalNetworks
		*out = make([]VPNLocalNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(VPNGatewayMTU)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(RouterPodSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCVPNGatewaySpec.
func (in *VPCVPNGatewaySpec) DeepCopy() *VPCVPNGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(VPCVPNGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCVPNGatewayStatus) DeepCopyInto(out *VPCVPNGatewayStatus) {
	*out = *in
	if in.Tunnels != nil {
		in, out := &in.Tunnels, &out.Tunnels
		*out = make([]VPNTunnelStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdvertisedRoutes != nil {
		in, out := &in.AdvertisedRoutes, &out.AdvertisedRoutes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCVPNGatewayStatus.
func (in *VPCVPNGatewayStatus) DeepCopy() *VPCVPNGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(VPCVPNGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNGatewayMTU) DeepCopyInto(out *VPNGatewayMTU) {
	*out = *in
	if in.TunnelMTU != nil {
		in, out := &in.TunnelMTU, &out.TunnelMTU
		*out = new(int32)
		**out = **in
	}
	if in.MSSClamp != nil {
		in, out := &in.MSSClamp, &out.MSSClamp
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNGatewayMTU.
func (in *VPNGatewayMTU) DeepCopy() *VPNGatewayMTU {
	if in == nil {
		return nil
	}
	out := new(VPNGatewayMTU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNIPsecConfig) DeepCopyInto(out *VPNIPsecConfig) {
	*out = *in
	if in.IKEPolicy != nil {
		in, out := &in.IKEPolicy, &out.IKEPolicy
		*out = new(VPNIPsecPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.IPsecPolicy != nil {
		in, out := &in.IPsecPolicy, &out.IPsecPolicy
		*out = new(VPNIPsecPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNIPsecConfig.
func (in *VPNIPsecConfig) DeepCopy() *VPNIPsecConfig {
	if in == nil {
		return nil
	}
	out := new(VPNIPsecConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNIPsecPolicy) DeepCopyInto(out *VPNIPsecPolicy) {
	*out = *in
	if in.IKEVersion != nil {
		in, out := &in.IKEVersion, &out.IKEVersion
		*out = new(int32)
		**out = **in
	}
	if in.DHGroup != nil {
		in, out := &in.DHGroup, &out.DHGroup
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNIPsecPolicy.
func (in *VPNIPsecPolicy) DeepCopy() *VPNIPsecPolicy {
	if in == nil {
		return nil
	}
	out := new(VPNIPsecPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNLocalNetwork) DeepCopyInto(out *VPNLocalNetwork) {
	*out = *in
	if in.NetworkRef != nil {
		in, out := &in.NetworkRef, &out.NetworkRef
		*out = new(BridgeNetworkRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNLocalNetwork.
func (in *VPNLocalNetwork) DeepCopy() *VPNLocalNetwork {
	if in == nil {
		return nil
	}
	out := new(VPNLocalNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNRemoteAccess) DeepCopyInto(out *VPNRemoteAccess) {
	*out = *in
	if in.DNSServers != nil {
		in, out := &in.DNSServers, &out.DNSServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxClients != nil {
		in, out := &in.MaxClients, &out.MaxClients
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNRemoteAccess.
func (in *VPNRemoteAccess) DeepCopy() *VPNRemoteAccess {
	if in == nil {
		return nil
	}
	out := new(VPNRemoteAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNTunnel) DeepCopyInto(out *VPNTunnel) {
	*out = *in
	if in.RemoteNetworks != nil {
		in, out := &in.RemoteNetworks, &out.RemoteNetworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PresharedKey != nil {
		in, out := &in.PresharedKey, &out.PresharedKey
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNTunnel.
func (in *VPNTunnel) DeepCopy() *VPNTunnel {
	if in == nil {
		return nil
	}
	out := new(VPNTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNTunnelStatus) DeepCopyInto(out *VPNTunnelStatus) {
	*out = *in
	if in.LastHandshake != nil {
		in, out := &in.LastHandshake, &out.LastHandshake
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNTunnelStatus.
func (in *VPNTunnelStatus) DeepCopy() *VPNTunnelStatus {
	if in == nil {
		return nil
	}
	out := new(VPNTunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNWireGuardConfig) DeepCopyInto(out *VPNWireGuardConfig) {
	*out = *in
	out.PrivateKey = in.PrivateKey
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNWireGuardConfig.
func (in *VPNWireGuardConfig) DeepCopy() *VPNWireGuardConfig {
	if in == nil {
		return nil
	}
	out := new(VPNWireGuardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCRouteSpec) DeepCopyInto(out *VPCRouteSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCRouteSpec.
func (in *VPCRouteSpec) DeepCopy() *VPCRouteSpec {
	if in == nil {
		return nil
	}
	out := new(VPCRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCRouter) DeepCopyInto(out *VPCRouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCRouter.
func (in *VPCRouter) DeepCopy() *VPCRouter {
	if in == nil {
		return nil
	}
	out := new(VPCRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCRouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCRouterList) DeepCopyInto(out *VPCRouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCRouterList.
func (in *VPCRouterList) DeepCopy() *VPCRouterList {
	if in == nil {
		return nil
	}
	out := new(VPCRouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCRouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCRouterSpec) DeepCopyInto(out *VPCRouterSpec) {
	*out = *in
	if in.Transit != nil {
		in, out := &in.Transit, &out.Transit
		*out = new(RouterTransit)
		**out = **in
	}
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]RouterNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RouteAdvertisement != nil {
		in, out := &in.RouteAdvertisement, &out.RouteAdvertisement
		*out = new(RouteAdvertisement)
		**out = **in
	}
	if in.DHCP != nil {
		in, out := &in.DHCP, &out.DHCP
		*out = new(RouterDHCP)
		(*in).DeepCopyInto(*out)
	}
	if in.Firewall != nil {
		in, out := &in.Firewall, &out.Firewall
		*out = new(GatewayFirewall)
		(*in).DeepCopyInto(*out)
	}
	if in.IDS != nil {
		in, out := &in.IDS, &out.IDS
		*out = new(RouterIDS)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(RouterPodSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCRouterSpec.
func (in *VPCRouterSpec) DeepCopy() *VPCRouterSpec {
	if in == nil {
		return nil
	}
	out := new(VPCRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCRouterStatus) DeepCopyInto(out *VPCRouterStatus) {
	*out = *in
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]RouterNetworkStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdvertisedRoutes != nil {
		in, out := &in.AdvertisedRoutes, &out.AdvertisedRoutes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCRouterStatus.
func (in *VPCRouterStatus) DeepCopy() *VPCRouterStatus {
	if in == nil {
		return nil
	}
	out := new(VPCRouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCSubnet) DeepCopyInto(out *VPCSubnet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCSubnet.
func (in *VPCSubnet) DeepCopy() *VPCSubnet {
	if in == nil {
		return nil
	}
	out := new(VPCSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCSubnet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCSubnetList) DeepCopyInto(out *VPCSubnetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCSubnetList.
func (in *VPCSubnetList) DeepCopy() *VPCSubnetList {
	if in == nil {
		return nil
	}
	out := new(VPCSubnetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCSubnetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCSubnetSpec) DeepCopyInto(out *VPCSubnetSpec) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VLANID != nil {
		in, out := &in.VLANID, &out.VLANID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCSubnetSpec.
func (in *VPCSubnetSpec) DeepCopy() *VPCSubnetSpec {
	if in == nil {
		return nil
	}
	out := new(VPCSubnetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCSubnetStatus) DeepCopyInto(out *VPCSubnetStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCSubnetStatus.
func (in *VPCSubnetStatus) DeepCopy() *VPCSubnetStatus {
	if in == nil {
		return nil
	}
	out := new(VPCSubnetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNetworkInterface) DeepCopyInto(out *VirtualNetworkInterface) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNetworkInterface.
func (in *VirtualNetworkInterface) DeepCopy() *VirtualNetworkInterface {
	if in == nil {
		return nil
	}
	out := new(VirtualNetworkInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualNetworkInterface) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNetworkInterfaceList) DeepCopyInto(out *VirtualNetworkInterfaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualNetworkInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNetworkInterfaceList.
func (in *VirtualNetworkInterfaceList) DeepCopy() *VirtualNetworkInterfaceList {
	if in == nil {
		return nil
	}
	out := new(VirtualNetworkInterfaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualNetworkInterfaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
